# Generated by Django 5.2.12 on 2026-04-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['management__name', 'name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['name'], 'verbose_name': 'Управление', 'verbose_name_plural': 'Управления'},
        ),
    ]
