# Generated by Django 5.2.12 on 2026-03-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('short_fio', models.CharField(blank=True, max_length=255)),
                ('personnel_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'middle_name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_units', to='organization.department')),
                ('staff_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_units', to='staff.position')),
            ],
            options={
                'ordering': ['department__name', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff.employee')),
                ('actual_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_assignments', to='staff.position')),
                ('staff_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff.staffunit')),
            ],
            options={
                'ordering': ['-is_current', '-start_date', 'employee__last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffunit',
            constraint=models.UniqueConstraint(fields=('department', 'unit_number'), name='uniq_staff_unit_number_per_department'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('employee',), name='uniq_current_assignment_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeeassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('staff_unit',), name='uniq_current_assignment_per_staff_unit'),
        ),
    ]
