# Generated by Codex on 2026-03-30

from django.db import migrations, models


def populate_position_hierarchy(apps, schema_editor):
    Position = apps.get_model("staff", "Position")
    mapping = {
        "Начальник отдела": 10,
        "Заместитель начальника отдела": 20,
        "Главный специалист": 30,
        "Ведущий специалист": 40,
        "Старший инспектор": 50,
        "Инспектор": 60,
        "Старший инженер": 70,
        "Инженер": 80,
        "Старший бухгалтер": 90,
        "Бухгалтер": 100,
        "Администратор": 110,
    }
    for position in Position.objects.all():
        position.hierarchy_order = mapping.get(position.name, 100)
        position.save(update_fields=["hierarchy_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="hierarchy_order",
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["hierarchy_order", "name"]},
        ),
        migrations.RunPython(populate_position_hierarchy, migrations.RunPython.noop),
    ]
