# Generated by Codex on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_position_hierarchy_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="hierarchy_order",
            field=models.PositiveIntegerField(),
        ),
    ]
