# Generated by Codex on 2026-03-30

from django.db import migrations


def convert_hierarchy_to_tariff_grade(apps, schema_editor):
    Position = apps.get_model("staff", "Position")
    mapping = {
        "Начальник отдела": 110,
        "Главный специалист": 90,
        "Инспектор": 60,
        "Инженер": 40,
        "Бухгалтер": 20,
        "Администратор": 10,
    }
    for position in Position.objects.all():
        if position.name in mapping:
            position.hierarchy_order = mapping[position.name]
            position.save(update_fields=["hierarchy_order"])


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0003_alter_position_hierarchy_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="position",
            options={"ordering": ["-hierarchy_order", "name"]},
        ),
        migrations.RunPython(convert_hierarchy_to_tariff_grade, migrations.RunPython.noop),
    ]
