# Generated by Codex on 2026-03-30

from django.db import migrations


def apply_tariff_grade_values(apps, schema_editor):
    Position = apps.get_model("staff", "Position")
    mapping = {
        "Начальник отдела": 110,
        "Главный специалист": 90,
        "Инспектор": 60,
        "Инженер": 40,
        "Бухгалтер": 20,
        "Администратор": 10,
    }
    for name, value in mapping.items():
        Position.objects.filter(name=name).update(hierarchy_order=value)


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_tariff_grade_semantics"),
    ]

    operations = [
        migrations.RunPython(apply_tariff_grade_values, migrations.RunPython.noop),
    ]
