# Generated by Django 5.2.12 on 2026-04-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_fix_tariff_grade_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name', 'middle_name'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeassignment',
            options={'ordering': ['-is_current', '-start_date', 'employee__last_name'], 'verbose_name': 'Назначение сотрудника', 'verbose_name_plural': 'Назначения сотрудников'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-hierarchy_order', 'name'], 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='staffunit',
            options={'ordering': ['department__name', 'unit_number'], 'verbose_name': 'Штатная единица', 'verbose_name_plural': 'Штатные единицы'},
        ),
    ]
