# Generated by Django 5.2.12 on 2026-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Руководитель')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='scope_type',
            field=models.CharField(choices=[('all', 'Все'), ('management', 'Управление'), ('department', 'Отдел')], default='all', max_length=20),
        ),
    ]
