# Generated by Django 5.2.12 on 2026-03-29 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_absence_reasons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_attendance_sheets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_sheets', to='organization.department')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_attendance_sheets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceSheetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('absence_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_items', to='attendance.absencereason')),
                ('attendance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='attendance.attendancesheet')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_items', to='staff.employee')),
            ],
            options={
                'ordering': ['employee__last_name', 'employee__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancesheet',
            constraint=models.UniqueConstraint(fields=('date', 'department'), name='uniq_sheet_per_day_department'),
        ),
        migrations.AddConstraint(
            model_name='attendancesheetitem',
            constraint=models.UniqueConstraint(fields=('attendance_sheet', 'employee'), name='uniq_employee_per_sheet'),
        ),
    ]
