# Generated by Django 5.2.12 on 2026-04-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='absencereason',
            options={'ordering': ['name'], 'verbose_name': 'Причина отсутствия', 'verbose_name_plural': 'Причины отсутствия'},
        ),
        migrations.AlterModelOptions(
            name='attendancesheet',
            options={'ordering': ['-date', 'department__name'], 'verbose_name': 'Табель', 'verbose_name_plural': 'Табели'},
        ),
        migrations.AlterModelOptions(
            name='attendancesheetitem',
            options={'ordering': ['employee__last_name', 'employee__first_name'], 'verbose_name': 'Строка табеля', 'verbose_name_plural': 'Строки табеля'},
        ),
        migrations.AlterField(
            model_name='attendancesheetitem',
            name='status',
            field=models.CharField(choices=[('present', 'Присутствует'), ('absent', 'Отсутствует')], default='present', max_length=20),
        ),
    ]
